# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tools/requirements.txt
    - name: parse json
      run: python tools/parseJson.py

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    # Cache the build dependencies
    - name: Cache
      uses: actions/cache@v2.1.0
      with:
        path: |
          ~/cache
          !~/cache/exclude
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Install dependencies
      run: npm ci

    - name: lint
      run: npm run lint

    - name: Webpack build
      run: npm run build:prod

    - name: Upload webpack artifacts
      uses: actions/upload-artifact@v2
      with:
        name: webpack-artifacts
        path: dist

  deploy-us:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Setup SSH for target host
      uses: kielabokkie/ssh-key-and-known-hosts-action@v1.1.0
      with:
        # Private key required to access the host
        ssh-private-key: ${{ secrets.FISH_SSH }}
        # Hostname or IP to add to the known hosts file
        ssh-host: ${{ secrets.US_HOST }}

    - name: Download webpack artifacts
      uses: actions/download-artifact@v2
      with:
        path: dist
        name: webpack-artifacts

    - name: Upload to server
      env:
        HOST: ${{ secrets.US_HOST }}
      run: rsync -avz dist/ ubuntu@${HOST}:/var/www/data/relations/ --delete-after

  deploy-kr:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Setup SSH for target host
      uses: kielabokkie/ssh-key-and-known-hosts-action@v1.1.0
      with:
        # Private key required to access the host
        ssh-private-key: ${{ secrets.FISH_SSH }}
        # Hostname or IP to add to the known hosts file
        ssh-host: ${{ secrets.KR_HOST }}

    - name: Download webpack artifacts
      uses: actions/download-artifact@v2
      with:
        path: dist
        name: webpack-artifacts

    - name: Upload to server
      env:
        HOST: ${{ secrets.KR_HOST }}
      run: rsync -avz dist/ ubuntu@${HOST}:/var/www/relations/ --delete-after
